#!/usr/bin/env node
/**
 * Turn folders of photographs into the Gallery page.
 *
 *   assets/gallery/originals/<room-name>/*.jpg|png|webp      <- put your photos here
 *   assets/gallery/originals/<room-name>/room.json           <- optional: {"title":{"en":"…","zh":"…"},"note":{"en":"…","zh":"…"}}
 *   assets/gallery/originals/<room-name>/captions.json       <- optional: {"file-name.jpg":{"title":{"en":"…","zh":"…"},"place":"Stockholm","year":"2024"}}
 *
 *   npm i -D sharp      (once)
 *   node scripts/add-photos.mjs
 *
 * Writes assets/gallery/full/ (2000px), thumbs/ (1000px) and small/ (640px, used on the canvas) and regenerates
 * assets/js/gallery-data.js (keeps your hand-edited kicker/title/statement).
 * Photos sort by file name inside a room; rooms sort by folder name (prefix with 01-, 02- to order).
 * iPhone HEIC files: export as JPG first. Strips GPS/EXIF: only the resized copies are published.
 */
import { readdirSync, statSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";
import sharp from "sharp";

const ROOT = "assets/gallery", SRC = join(ROOT, "originals"), FULL = join(ROOT, "full"), THUMB = join(ROOT, "thumbs"), SMALL = join(ROOT, "small");
if (!existsSync(SRC)) { console.error(`Put photos in ${SRC}/<room-name>/ first.`); process.exit(1); }
mkdirSync(FULL, { recursive: true }); mkdirSync(THUMB, { recursive: true }); mkdirSync(SMALL, { recursive: true });

const slug = (s) => s.toLowerCase().normalize("NFKD").replace(/[^\w]+/g, "-").replace(/^-+|-+$/g, "") || "photo";
const readJson = (p, d) => { try { return JSON.parse(readFileSync(p, "utf8")); } catch { return d; } };
const pretty = (name) => ({ en: name.replace(/^\d+[-_ ]*/, "").replace(/[-_]+/g, " ").trim(), zh: name.replace(/^\d+[-_ ]*/, "").replace(/[-_]+/g, " ").trim() });

const series = [];
for (const room of readdirSync(SRC).filter((d) => statSync(join(SRC, d)).isDirectory()).sort()) {
  const dir = join(SRC, room);
  const meta = readJson(join(dir, "room.json"), {});
  const caps = readJson(join(dir, "captions.json"), {});
  const photos = [];
  for (const f of readdirSync(dir).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort()) {
    const id = slug(room + "-" + basename(f, extname(f)));
    const img = sharp(join(dir, f)).rotate();           // honour EXIF orientation
    const info = await img.clone().resize({ width: 2000, height: 2000, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 82, mozjpeg: true }).toFile(join(FULL, id + ".jpg"));
    await img.clone().resize({ width: 1000, height: 1000, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 78, mozjpeg: true }).toFile(join(THUMB, id + ".jpg"));
    await img.clone().resize({ width: 640, height: 640, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 74, mozjpeg: true }).toFile(join(SMALL, id + ".jpg"));
    const c = caps[f] || {};
    photos.push({ file: `assets/gallery/full/${id}.jpg`, thumb: `assets/gallery/thumbs/${id}.jpg`, small: `assets/gallery/small/${id}.jpg`, w: info.width, h: info.height, title: c.title || pretty(basename(f, extname(f))), place: c.place || "", year: c.year || "" });
    console.log("  +", room, f);
  }
  if (photos.length) series.push({ id: slug(room), title: meta.title || pretty(room), note: meta.note || { en: "", zh: "" }, photos });
}

// keep hand-edited header fields from the existing data file
let head = { kicker: { en: "Side project", zh: "个人项目" }, title: { en: "Gallery", zh: "摄影" }, statement: { en: "", zh: "" } };
try { const w = {}; new Function("window", readFileSync("assets/js/gallery-data.js", "utf8"))(w); head = { kicker: w.GALLERY.kicker, title: w.GALLERY.title, statement: w.GALLERY.statement }; } catch {}
const out = `/* GENERATED by scripts/add-photos.mjs — edit kicker/title/statement freely; the rest is rewritten on each run. */\nwindow.GALLERY = ${JSON.stringify({ ...head, series }, null, 2)};\n`;
writeFileSync("assets/js/gallery-data.js", out);
console.log(`Done: ${series.length} rooms, ${series.reduce((n, s) => n + s.photos.length, 0)} photographs.`);
